// apps/svelte/src/AmharicKeyboard.svelte
<script lang="ts">
  import { onMount, onDestroy, createEventDispatcher } from "svelte";
  import { amharicLayout } from "@amharic-keyboard/core";
  import type {
    KeyboardKey,
    KeyboardLayout,
    AmharicKeyboardProps,
    AmharicKeyboardAPI,
  } from "./types";
  import "./style.css";

  const dispatch = createEventDispatcher();

  export let targetInput: HTMLInputElement | HTMLTextAreaElement | undefined;
  export let targetInputs:
    | (HTMLInputElement | HTMLTextAreaElement)[]
    | undefined;
  export let layout: KeyboardLayout = amharicLayout;
  export let draggable = true;
  export let showHeader = true;
  export let minimizeButton = true;
  export let closeButton = false;
  export let minWidth = 300;
  export let minHeight = 200;
  export let maxWidth = 800;
  export let maxHeight = 500;
  export let className = "";
  export let style = "";

  // Internal state
  let value = "";
  let activeFamily: { value: string; children: string[] } | null = null;
  let currentChildren: string[] = [];
  let isDragging = false;
  let isResizing = false;
  let isMinimized = false;
  let isVisible = true;
  let position = { x: 20, y: 20 };
  let size = { width: minWidth, height: minHeight };
  let dragOffset = { x: 0, y: 0 };
  let resizeStart = { x: 0, y: 0, width: minWidth, height: minHeight };

  // Refs
  let keyboardElement: HTMLDivElement;
  let currentInput: HTMLInputElement | HTMLTextAreaElement | null = null;
  let inputs: (HTMLInputElement | HTMLTextAreaElement)[] = [];
  let cleanupFunctions: (() => void)[] = [];

  // API methods
  const api: AmharicKeyboardAPI = {
    addInput: (input: HTMLInputElement | HTMLTextAreaElement) => {
      if (!inputs.includes(input)) {
        inputs.push(input);
        setupInputListeners(input);

        if (!currentInput) {
          currentInput = input;
          value = input.value || "";
        }
        return true;
      }
      return false;
    },

    removeInput: (input: HTMLInputElement | HTMLTextAreaElement) => {
      const index = inputs.indexOf(input);
      if (index > -1) {
        inputs.splice(index, 1);
        cleanupInputListeners(input);

        if (currentInput === input) {
          currentInput = inputs[0] || null;
          value = currentInput?.value || "";
        }
        return true;
      }
      return false;
    },

    switchToInput: (input: HTMLInputElement | HTMLTextAreaElement) => {
      if (currentInput !== input && inputs.includes(input)) {
        currentInput = input;
        value = input.value;
        activeFamily = null;
        currentChildren = [];

        if (keyboardElement) {
          keyboardElement.style.opacity = "1";
        }
        return true;
      }
      return false;
    },

    getCurrentInput: () => currentInput,

    getAllInputs: () => [...inputs],

    show: () => {
      isVisible = true;
      isMinimized = false;
    },

    hide: () => {
      isVisible = false;
    },

    toggleMinimize: () => {
      isMinimized = !isMinimized;
    },

    moveTo: (x: number, y: number) => {
      position = { x, y };
    },

    resize: (width: number, height: number) => {
      const newWidth = Math.max(minWidth, Math.min(width, maxWidth));
      const newHeight = Math.max(minHeight, Math.min(height, maxHeight));
      size = { width: newWidth, height: newHeight };
    },

    syncInput: () => {
      if (currentInput) {
        value = currentInput.value;
      }
    },

    getValue: () => value,
  };

  // Expose API
  export { api };

  // Setup input listeners
  function setupInputListeners(input: HTMLInputElement | HTMLTextAreaElement) {
    const focusHandler = () => {
      if (currentInput !== input && inputs.includes(input)) {
        currentInput = input;
        value = input.value;
        activeFamily = null;
        currentChildren = [];

        if (keyboardElement) {
          keyboardElement.style.opacity = "1";
        }
      }
    };

    const inputHandler = () => {
      if (currentInput === input) {
        value = input.value;
      }
    };

    input.addEventListener("focus", focusHandler);
    input.addEventListener("input", inputHandler);
    input.addEventListener("change", inputHandler);

    cleanupFunctions.push(() => {
      input.removeEventListener("focus", focusHandler);
      input.removeEventListener("input", inputHandler);
      input.removeEventListener("change", inputHandler);
    });
  }

  // Cleanup input listeners
  function cleanupInputListeners(
    input: HTMLInputElement | HTMLTextAreaElement,
  ) {
    // Clone and replace to remove all listeners
    const parent = input.parentNode;
    if (parent) {
      const newInput = input.cloneNode(true) as
        | HTMLInputElement
        | HTMLTextAreaElement;
      newInput.value = input.value;
      parent.replaceChild(newInput, input);
    }
  }

  // Initialize
  onMount(() => {
    if (targetInputs && targetInputs.length > 0) {
      const validInputs = targetInputs.filter(
        (input): input is HTMLInputElement | HTMLTextAreaElement =>
          input != null && "addEventListener" in input,
      );

      inputs = validInputs;

      if (validInputs.length > 0) {
        currentInput = validInputs[0];
        value = currentInput?.value || "";

        validInputs.forEach((input) => setupInputListeners(input));
      }
    } else if (targetInput && "addEventListener" in targetInput) {
      inputs = [targetInput];
      setupInputListeners(targetInput);
      currentInput = targetInput;
      value = targetInput.value || "";
    }

    // Global click listener
    const handleDocumentClick = (e: MouseEvent) => {
      if (keyboardElement && !keyboardElement.contains(e.target as Node)) {
        keyboardElement.style.opacity = "0.7";
      }
    };

    document.addEventListener("click", handleDocumentClick);

    // Cleanup
    return () => {
      document.removeEventListener("click", handleDocumentClick);
      cleanupFunctions.forEach((cleanup) => cleanup());
      cleanupFunctions = [];
    };
  });

  // Drag functionality
  let dragMoveHandler: (e: MouseEvent) => void;
  let dragEndHandler: () => void;

  function handleDragStart(e: MouseEvent) {
    if (!draggable || !keyboardElement) return;

    const target = e.target as HTMLElement;
    if (
      target.tagName === "BUTTON" ||
      target.classList.contains("resize-handle")
    ) {
      return;
    }

    e.preventDefault();
    isDragging = true;
    const rect = keyboardElement.getBoundingClientRect();
    dragOffset = {
      x: e.clientX - rect.left,
      y: e.clientY - rect.top,
    };

    dragMoveHandler = (moveEvent: MouseEvent) => {
      if (!isDragging) return;
      moveEvent.preventDefault();

      const x = moveEvent.clientX - dragOffset.x;
      const y = moveEvent.clientY - dragOffset.y;

      const keyboardWidth = keyboardElement.offsetWidth;
      const keyboardHeight = keyboardElement.offsetHeight;
      const maxX = window.innerWidth - keyboardWidth;
      const maxY = window.innerHeight - keyboardHeight;

      const boundedX = Math.max(0, Math.min(x, maxX));
      const boundedY = Math.max(0, Math.min(y, maxY));

      position = { x: boundedX, y: boundedY };
    };

    dragEndHandler = () => {
      isDragging = false;
      document.removeEventListener("mousemove", dragMoveHandler);
      document.removeEventListener("mouseup", dragEndHandler);
    };

    document.addEventListener("mousemove", dragMoveHandler);
    document.addEventListener("mouseup", dragEndHandler);
  }

  // Resize functionality
  let resizeMoveHandler: (e: MouseEvent) => void;
  let resizeEndHandler: () => void;

  function handleResizeStart(e: MouseEvent) {
    e.preventDefault();
    e.stopPropagation();

    isResizing = true;
    resizeStart = {
      x: e.clientX,
      y: e.clientY,
      width: size.width,
      height: size.height,
    };

    resizeMoveHandler = (moveEvent: MouseEvent) => {
      if (!isResizing) return;
      moveEvent.preventDefault();

      const deltaX = moveEvent.clientX - resizeStart.x;
      const deltaY = moveEvent.clientY - resizeStart.y;

      let newWidth = resizeStart.width + deltaX;
      let newHeight = resizeStart.height + deltaY;

      newWidth = Math.max(minWidth, Math.min(newWidth, maxWidth));
      newHeight = Math.max(minHeight, Math.min(newHeight, maxHeight));

      const maxViewportWidth = window.innerWidth * 0.9;
      const maxViewportHeight = window.innerHeight * 0.9;
      newWidth = Math.min(newWidth, maxViewportWidth);
      newHeight = Math.min(newHeight, maxViewportHeight);

      size = { width: newWidth, height: newHeight };

      if (keyboardElement) {
        const rect = keyboardElement.getBoundingClientRect();
        if (rect.right > window.innerWidth) {
          const newLeft = window.innerWidth - newWidth;
          position = { ...position, x: Math.max(0, newLeft) };
        }

        if (rect.bottom > window.innerHeight) {
          const newTop = window.innerHeight - newHeight;
          position = { ...position, y: Math.max(0, newTop) };
        }
      }
    };

    resizeEndHandler = () => {
      isResizing = false;
      document.removeEventListener("mousemove", resizeMoveHandler);
      document.removeEventListener("mouseup", resizeEndHandler);
    };

    document.addEventListener("mousemove", resizeMoveHandler);
    document.addEventListener("mouseup", resizeEndHandler);
  }

  // Keyboard input handling
  function syncInput(newValue: string) {
    if (currentInput) {
      currentInput.value = newValue;
      currentInput.focus();
      currentInput.dispatchEvent(new Event("input", { bubbles: true }));
      value = currentInput.value;
    }
  }

  function insertCharacter(char: string) {
    const newValue = value + char;
    value = newValue;
    syncInput(newValue);
  }

  function handleKeyPress(key: KeyboardKey) {
    if (!currentInput) return;

    if (key.type === "char" && key.children?.length) {
      activeFamily = { value: key.value, children: key.children };
      insertCharacter(key.value);
      currentChildren = [key.value, ...key.children];
      return;
    }

    activeFamily = null;
    currentChildren = [];

    if (key.type === "char" || key.type === "point") {
      insertCharacter(key.value || "");
    } else if (key.type === "space") {
      insertCharacter(" ");
    } else if (key.type === "enter") {
      insertCharacter("\n");
    } else if (key.type === "backspace") {
      const newValue = value.slice(0, -1);
      value = newValue;
      syncInput(newValue);
    }
  }

  function handleChildButtonClick(char: string) {
    if (!char || !activeFamily) return;

    const isSameFamily = [
      activeFamily.value,
      ...activeFamily.children,
    ].includes(char);

    if (isSameFamily) {
      const newValue = value.slice(0, -1) + char;
      value = newValue;
      syncInput(newValue);
    } else {
      insertCharacter(char);
    }
  }

  function handleClose() {
    dispatch("close");
  }

  // Cleanup drag/resize handlers
  onDestroy(() => {
    if (dragMoveHandler) {
      document.removeEventListener("mousemove", dragMoveHandler);
    }
    if (dragEndHandler) {
      document.removeEventListener("mouseup", dragEndHandler);
    }
    if (resizeMoveHandler) {
      document.removeEventListener("mousemove", resizeMoveHandler);
    }
    if (resizeEndHandler) {
      document.removeEventListener("mouseup", resizeEndHandler);
    }
  });

  // Keyboard style
  $: keyboardStyle = `
    position: fixed;
    left: ${position.x}px;
    top: ${position.y}px;
    width: ${size.width}px;
    height: ${size.height}px;
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 0px 10px;
    background: #e0e0e0;
    border: 1px solid #ccc;
    border-radius: 5px;
    z-index: 10000;
    box-shadow: 0 4px 20px rgba(0,0,0,0.2);
    user-select: none;
    transition: ${isDragging || isResizing ? "none" : "all 0.3s ease"};
    cursor: ${isDragging ? "grabbing" : "default"};
    overflow: hidden;
    ${style}
  `;
</script>

{#if !isVisible}
  <!-- Hidden -->
{:else if isMinimized}
  <div
    class="amharic-virtual-keyboard-minimized"
    style="
      position: fixed;
      bottom: 20px;
      right: 20px;
      width: 60px;
      height: 60px;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      background: #2c3e50;
      color: white;
      cursor: pointer;
      z-index: 10000;
      box-shadow: 0 2px 10px rgba(0,0,0,0.3);
      font-size: 24px;
      user-select: none;
      transition: all 0.3s ease;
    "
    on:click={() => (isMinimized = false)}
    on:mouseenter={(e) => {
      e.currentTarget.style.transform = "scale(1.1)";
      e.currentTarget.style.boxShadow = "0 4px 15px rgba(0,0,0,0.4)";
    }}
    on:mouseleave={(e) => {
      e.currentTarget.style.transform = "scale(1)";
      e.currentTarget.style.boxShadow = "0 2px 10px rgba(0,0,0,0.3)";
    }}
    title="Click to restore Amharic Keyboard"
  >
    ⌨
  </div>
{:else}
  <div
    bind:this={keyboardElement}
    class="amharic-virtual-keyboard {className}"
    style={keyboardStyle}
  >
    {#if showHeader}
      <div
        class="keyboard-header"
        style="
          width: 100%;
          padding: 8px 12px;
          background: #2c3e50;
          color: white;
          display: flex;
          justify-content: space-between;
          align-items: center;
          cursor: {draggable ? 'move' : 'default'};
          border-radius: 5px 5px 0 0;
          margin-bottom: 10px;
          user-select: none;
        "
        on:mousedown={handleDragStart}
      >
        <span style="font-weight: bold">Amharic Keyboard</span>
        <div style="display: flex; gap: 8px">
          {#if minimizeButton}
            <button
              on:click={() => (isMinimized = true)}
              style="
                background: transparent;
                border: 1px solid rgba(255,255,255,0.3);
                color: white;
                cursor: pointer;
                width: 24px;
                height: 24px;
                border-radius: 3px;
                display: flex;
                align-items: center;
                justify-content: center;
                font-size: 18px;
              "
            >
              −
            </button>
          {/if}
          {#if closeButton}
            <button
              on:click={handleClose}
              style="
                background: transparent;
                border: 1px solid rgba(255,255,255,0.3);
                color: white;
                cursor: pointer;
                width: 24px;
                height: 24px;
                border-radius: 3px;
                display: flex;
                align-items: center;
                justify-content: center;
                font-size: 18px;
              "
            >
              ×
            </button>
          {/if}
        </div>
      </div>
    {/if}

    <!-- Child buttons -->
    <div
      style="
        display: flex;
        justify-content: center;
        margin-bottom: 10px;
        width: 100%;
        flex-wrap: wrap;
        gap: 2px;
      "
    >
      {#each Array.from({ length: 8 }) as _, i}
        {#if currentChildren[i]}
          <button
            class="keyboard-child-button"
            style="
        margin: 2px;
        padding: 10px;
        min-width: 40px;
        min-height: 40px;
        font-size: 18px;
        cursor: pointer;
        background: #d3d3d3;
        border: 1px solid #ccc;
        border-radius: 3px;
        opacity: 1;
      "
            on:click={() => handleChildButtonClick(currentChildren[i])}
          >
            {currentChildren[i]}
          </button>
        {:else}
          <button
            class="keyboard-child-button"
            style="
        margin: 2px;
        padding: 10px;
        min-width: 40px;
        min-height: 40px;
        font-size: 18px;
        cursor: pointer;
        background: #e0e0e0;
        border: 1px solid #ccc;
        border-radius: 3px;
        opacity: 0.5;
      "
            disabled
          >
            <!-- empty button -->
          </button>
        {/if}
      {/each}
    </div>

    <!-- Keyboard rows -->
    {#each layout as row, rowIndex}
      <div
        style="
          display: flex;
          justify-content: center;
          margin-bottom: 5px;
          width: 100%;
        "
      >
        {#each row as key, keyIndex}
          <button
            class="keyboard-key"
            style="
              margin: 2px;
              padding: 8px;
              min-width: 35px;
              min-height: 40px;
              font-size: 16px;
              cursor: pointer;
              border: 1px solid #ccc;
              border-radius: 3px;
              background: white;
              flex: 1;
            "
            on:click={() => handleKeyPress(key)}
          >
            {key.label}
          </button>
        {/each}
      </div>
    {/each}

    <!-- Resize handle -->
    <div
      class="resize-handle"
      style="
        position: absolute;
        bottom: 0;
        right: 0;
        width: 20px;
        height: 20px;
        cursor: se-resize;
        background: linear-gradient(135deg, transparent 50%, #888 50%);
      "
      on:mousedown={handleResizeStart}
    />
  </div>
{/if}

// packages/react/src/AmharicKeyboard.tsx
import React, {
  useState,
  useEffect,
  useRef,
  useCallback,
  useImperativeHandle,
  forwardRef
} from 'react';
import { amharicLayout } from '../../core/layouts/amharic';
import type { ActiveFamily, AmharicKeyboardProps, } from '../../core/types';
import type { AmharicKeyboardRef } from '../types/'
import './AmharicKeyboard.css';

export const AmharicKeyboard = forwardRef<AmharicKeyboardRef, AmharicKeyboardProps>(
  ({
    targetInput,
    targetInputs,
    layout = amharicLayout,
    draggable = true,
    showHeader = true,
    minimizeButton = true,
    closeButton = false,
    minWidth = 300,
    minHeight = 200,
    maxWidth = 800,
    maxHeight = 500,
    onClose,
    className = '',
    style = {},
    children
  }, ref) => {
    const [value, setValue] = useState<string>('');
    const [activeFamily, setActiveFamily] = useState<ActiveFamily | null>(null);
    const [currentChildren, setCurrentChildren] = useState<string[]>([]);
    const [isDragging, setIsDragging] = useState(false);
    const [isResizing, setIsResizing] = useState(false);
    const [isMinimized, setIsMinimized] = useState(false);
    const [isVisible, setIsVisible] = useState(true);
    const [position, setPosition] = useState({ x: 20, y: 20 });
    const [size, setSize] = useState({ width: minWidth, height: minHeight });
    const [dragOffset, setDragOffset] = useState({ x: 0, y: 0 });
    const [resizeStart, setResizeStart] = useState({
      x: 0,
      y: 0,
      width: minWidth,
      height: minHeight
    });

    const keyboardRef = useRef<HTMLDivElement>(null);
    const headerRef = useRef<HTMLDivElement>(null);
    const resizeHandleRef = useRef<HTMLDivElement>(null);
    const currentInputRef = useRef<HTMLInputElement | HTMLTextAreaElement | null>(null);
    const inputsRef = useRef<(HTMLInputElement | HTMLTextAreaElement)[]>([]);
    const inputHandlersRef = useRef<Map<
      HTMLInputElement | HTMLTextAreaElement,
      { focus: () => void; input: () => void; change: () => void; cut: () => void; paste: () => void }
    >>(new Map());

    useImperativeHandle(ref, () => ({
      addInput: (input: HTMLInputElement | HTMLTextAreaElement) => {
        if (!inputsRef.current.includes(input)) {
          inputsRef.current.push(input);
          setupInputListeners(input);

          if (!currentInputRef.current) {
            currentInputRef.current = input;
            setValue(input.value || '');
          }
          return true;
        }
        return false;
      },

      removeInput: (input: HTMLInputElement | HTMLTextAreaElement) => {
        const index = inputsRef.current.indexOf(input);
        if (index > -1) {
          inputsRef.current.splice(index, 1);
          cleanupInputListeners(input);

          if (currentInputRef.current === input) {
            currentInputRef.current = inputsRef.current[0] || null;
            setValue(currentInputRef.current?.value || '');
          }
          return true;
        }
        return false;
      },

      switchToInput: (input: HTMLInputElement | HTMLTextAreaElement) => {
        if (currentInputRef.current !== input && inputsRef.current.includes(input)) {
          currentInputRef.current = input;
          setValue(input.value);
          setActiveFamily(null);
          setCurrentChildren([]);

          if (keyboardRef.current) {
            keyboardRef.current.style.opacity = '1';
          }
          return true;
        }
        return false;
      },

      getCurrentInput: () => currentInputRef.current,

      getAllInputs: () => [...inputsRef.current],

      show: () => {
        setIsVisible(true);
        setIsMinimized(false);
      },

      hide: () => {
        setIsVisible(false);
      },

      toggleMinimize: () => {
        setIsMinimized(!isMinimized);
      },

      moveTo: (x: number, y: number) => {
        setPosition({ x, y });
      },

      resize: (width: number, height: number) => {
        const newWidth = Math.max(minWidth, Math.min(width, maxWidth));
        const newHeight = Math.max(minHeight, Math.min(height, maxHeight));
        setSize({ width: newWidth, height: newHeight });
      },

      syncInput: () => {
        if (currentInputRef.current) {
          setValue(currentInputRef.current.value);
        }
      },

      getValue: () => value
    }));

    const setupInputListeners = useCallback((input: HTMLInputElement | HTMLTextAreaElement) => {
      const focusHandler = () => {
        if (currentInputRef.current !== input && inputsRef.current.includes(input)) {
          currentInputRef.current = input;
          setValue(input.value);
          setActiveFamily(null);
          setCurrentChildren([]);

          if (keyboardRef.current) {
            keyboardRef.current.style.opacity = '1';
          }
        }
      };

      const inputHandler = () => {
        if (currentInputRef.current === input) {
          setValue(input.value);
        }
      };

      const changeHandler = () => {
        if (currentInputRef.current === input) {
          setValue(input.value);
        }
      };

      const cutHandler = () => {
        if (currentInputRef.current === input) {
          setTimeout(() => {
            setValue(input.value);
          }, 0);
        }
      };

      const pasteHandler = () => {
        if (currentInputRef.current === input) {
          setTimeout(() => {
            setValue(input.value);
          }, 0);
        }
      };

      // Store handlers
      inputHandlersRef.current.set(input, {
        focus: focusHandler,
        input: inputHandler,
        change: changeHandler,
        cut: cutHandler,
        paste: pasteHandler
      });

      // Add listeners
      input.addEventListener('focus', focusHandler);
      input.addEventListener('input', inputHandler);
      input.addEventListener('change', changeHandler);
      input.addEventListener('cut', cutHandler);
      input.addEventListener('paste', pasteHandler);
    }, []);

    const cleanupInputListeners = useCallback((input: HTMLInputElement | HTMLTextAreaElement) => {
      const handlers = inputHandlersRef.current.get(input);
      if (handlers) {
        input.removeEventListener('focus', handlers.focus);
        input.removeEventListener('input', handlers.input);
        input.removeEventListener('change', handlers.change);
        input.removeEventListener('cut', handlers.cut);
        input.removeEventListener('paste', handlers.paste);
        inputHandlersRef.current.delete(input);
      }
    }, []);

    useEffect(() => {
      if (targetInputs) {
        const validInputs = targetInputs.filter(input => input !== null && input !== undefined);
        inputsRef.current = validInputs;

        if (validInputs.length > 0) {
          currentInputRef.current = validInputs[0];
          setValue(currentInputRef.current.value || '');

          validInputs.forEach(input => {
            if (input) {
              setupInputListeners(input);
            }
          });
        }
      } else if (targetInput) {
        inputsRef.current = [targetInput];
        setupInputListeners(targetInput);
        currentInputRef.current = targetInput;
        setValue(targetInput.value || '');
      }

      const handleDocumentClick = (e: MouseEvent) => {
        if (keyboardRef.current && !keyboardRef.current.contains(e.target as Node)) {
          keyboardRef.current.style.opacity = '0.7';
        }
      };

      document.addEventListener('click', handleDocumentClick);

      return () => {
        document.removeEventListener('click', handleDocumentClick);
        // Clean up all input listeners
        inputsRef.current.forEach(input => cleanupInputListeners(input));
        inputHandlersRef.current.clear();
      };
    }, [targetInput, targetInputs, setupInputListeners, cleanupInputListeners]);

    // Drag functionality
    const handleDragStart = useCallback((e: React.MouseEvent) => {
      if (!draggable || !keyboardRef.current) return;

      const target = e.target as HTMLElement;
      if (target.tagName === 'BUTTON' || target.classList.contains('resize-handle')) {
        return;
      }

      setIsDragging(true);
      const rect = keyboardRef.current.getBoundingClientRect();
      setDragOffset({
        x: e.clientX - rect.left,
        y: e.clientY - rect.top
      });
    }, [draggable]);

    useEffect(() => {
      const handleDragMove = (e: MouseEvent) => {
        if (!isDragging || !keyboardRef.current) return;

        e.preventDefault();

        const x = e.clientX - dragOffset.x;
        const y = e.clientY - dragOffset.y;

        const keyboardWidth = keyboardRef.current.offsetWidth;
        const keyboardHeight = keyboardRef.current.offsetHeight;
        const maxX = window.innerWidth - keyboardWidth;
        const maxY = window.innerHeight - keyboardHeight;

        const boundedX = Math.max(0, Math.min(x, maxX));
        const boundedY = Math.max(0, Math.min(y, maxY));

        setPosition({ x: boundedX, y: boundedY });
      };

      const handleDragEnd = () => {
        setIsDragging(false);
      };

      if (isDragging) {
        document.addEventListener('mousemove', handleDragMove);
        document.addEventListener('mouseup', handleDragEnd);
      }

      return () => {
        document.removeEventListener('mousemove', handleDragMove);
        document.removeEventListener('mouseup', handleDragEnd);
      };
    }, [isDragging, dragOffset]);

    // Resize functionality
    const handleResizeStart = useCallback((e: React.MouseEvent) => {
      e.preventDefault();
      e.stopPropagation();

      setIsResizing(true);
      setResizeStart({
        x: e.clientX,
        y: e.clientY,
        width: size.width,
        height: size.height
      });
    }, [size]);

    useEffect(() => {
      const handleResizeMove = (e: MouseEvent) => {
        if (!isResizing) return;

        e.preventDefault();

        const deltaX = e.clientX - resizeStart.x;
        const deltaY = e.clientY - resizeStart.y;

        let newWidth = resizeStart.width + deltaX;
        let newHeight = resizeStart.height + deltaY;

        newWidth = Math.max(minWidth, Math.min(newWidth, maxWidth));
        newHeight = Math.max(minHeight, Math.min(newHeight, maxHeight));

        const maxViewportWidth = window.innerWidth * 0.9;
        const maxViewportHeight = window.innerHeight * 0.9;
        newWidth = Math.min(newWidth, maxViewportWidth);
        newHeight = Math.min(newHeight, maxViewportHeight);

        setSize({ width: newWidth, height: newHeight });

        if (keyboardRef.current) {
          const rect = keyboardRef.current.getBoundingClientRect();
          if (rect.right > window.innerWidth) {
            const newLeft = window.innerWidth - newWidth;
            setPosition(pos => ({ ...pos, x: Math.max(0, newLeft) }));
          }

          if (rect.bottom > window.innerHeight) {
            const newTop = window.innerHeight - newHeight;
            setPosition(pos => ({ ...pos, y: Math.max(0, newTop) }));
          }
        }
      };

      const handleResizeEnd = () => {
        setIsResizing(false);
      };

      if (isResizing) {
        document.addEventListener('mousemove', handleResizeMove);
        document.addEventListener('mouseup', handleResizeEnd);
      }

      return () => {
        document.removeEventListener('mousemove', handleResizeMove);
        document.removeEventListener('mouseup', handleResizeEnd);
      };
    }, [isResizing, resizeStart, minWidth, minHeight, maxWidth, maxHeight]);

    // Keyboard input handling
    const insertCharacter = useCallback((char: string) => {
      const newValue = value + char;
      setValue(newValue);
      syncInput(newValue);
    }, [value]);

    const replaceLastCharacter = useCallback((char: string) => {
      const newValue = value.slice(0, -1) + char;
      setValue(newValue);
      syncInput(newValue);
    }, [value]);

    const syncInput = useCallback((newValue: string) => {
      if (currentInputRef.current) {
        currentInputRef.current.value = newValue;
        currentInputRef.current.focus();
        currentInputRef.current.dispatchEvent(new Event('input', { bubbles: true }));
        setValue(currentInputRef.current.value);
      }
    }, []);

    const handleKeyPress = useCallback((key: any) => {
      if (!currentInputRef.current) return;

      if (key.type === 'char' && key.children?.length) {
        const family = { value: key.value, children: key.children };
        setActiveFamily(family);
        insertCharacter(key.value);
        setCurrentChildren([key.value, ...key.children]);
        return;
      }

      setActiveFamily(null);
      setCurrentChildren([]);

      if (key.type === 'char' || key.type === 'point') {
        insertCharacter(key.value || '');
      } else if (key.type === 'space') {
        insertCharacter(' ');
      } else if (key.type === 'enter') {
        insertCharacter('\n');
      } else if (key.type === 'backspace') {
        const newValue = value.slice(0, -1);
        setValue(newValue);
        syncInput(newValue);
      }
    }, [value, insertCharacter, syncInput]);

    const isSameFamily = useCallback((char: string): boolean => {
      return !!activeFamily &&
        [activeFamily.value, ...activeFamily.children].includes(char);
    }, [activeFamily]);

    const handleChildButtonClick = useCallback((char: string, index: number) => {
      if (!char || !activeFamily) return;

      if (isSameFamily(char)) {
        replaceLastCharacter(char);
      } else {
        insertCharacter(char);
      }
    }, [activeFamily, isSameFamily, insertCharacter, replaceLastCharacter]);

    const toggleMinimize = useCallback(() => {
      setIsMinimized(!isMinimized);
    }, [isMinimized]);

    const handleClose = useCallback(() => {
      if (onClose) {
        onClose();
      }
    }, [onClose]);

    if (!isVisible) return null;

    if (isMinimized) {
      return (
        <div
          className="amharic-virtual-keyboard-minimized"
          style={{
            position: 'fixed',
            bottom: '20px',
            right: '20px',
            width: '60px',
            height: '60px',
            borderRadius: '50%',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            background: '#2c3e50',
            color: 'white',
            cursor: 'pointer',
            zIndex: 10000,
            boxShadow: '0 2px 10px rgba(0,0,0,0.3)',
            fontSize: '24px',
            userSelect: 'none',
            transition: 'all 0.3s ease'
          }}
          onClick={toggleMinimize}
          onMouseEnter={(e) => {
            const target = e.currentTarget;
            target.style.transform = 'scale(1.1)';
            target.style.boxShadow = '0 4px 15px rgba(0,0,0,0.4)';
          }}
          onMouseLeave={(e) => {
            const target = e.currentTarget;
            target.style.transform = 'scale(1)';
            target.style.boxShadow = '0 2px 10px rgba(0,0,0,0.3)';
          }}
          title="Click to restore Amharic Keyboard"
        >
          ⌨
        </div>
      );
    }

    const keyboardStyle: React.CSSProperties = {
      position: 'fixed',
      left: `${position.x}px`,
      top: `${position.y}px`,
      width: `${size.width}px`,
      height: `${size.height}px`,
      minWidth: `${minWidth}px`,
      minHeight: `${minHeight}px`,
      maxWidth: `${Math.min(maxWidth, window.innerWidth * 0.9)}px`,
      maxHeight: `${Math.min(maxHeight, window.innerHeight * 0.9)}px`,
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      padding: '0px 10px',
      background: '#e0e0e0',
      border: '1px solid #ccc',
      borderRadius: '5px',
      zIndex: 10000,
      boxShadow: '0 4px 20px rgba(0,0,0,0.2)',
      userSelect: 'none',
      transition: isDragging || isResizing ? 'none' : 'all 0.3s ease',
      cursor: isDragging ? 'grabbing' : 'default',
      overflow: 'hidden',
      opacity: 1,
      ...style
    };

    return (
      <div
        ref={keyboardRef}
        className={`amharic-virtual-keyboard ${className}`}
        style={keyboardStyle}
      >
        {showHeader && (
          <div
            ref={headerRef}
            className="keyboard-header"
            style={{
              width: '100%',
              padding: '8px 12px',
              background: '#2c3e50',
              color: 'white',
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
              cursor: draggable ? 'move' : 'default',
              borderRadius: '5px 5px 0 0',
              marginBottom: '10px',
              userSelect: 'none',
              flexShrink: 0
            }}
            onMouseDown={draggable ? handleDragStart : undefined}
          >
            <span style={{ fontWeight: 'bold' }}>Amharic Keyboard</span>
            <div style={{ display: 'flex', gap: '8px' }}>
              {minimizeButton && (
                <button
                  onClick={toggleMinimize}
                  style={{
                    background: 'transparent',
                    border: '1px solid rgba(255,255,255,0.3)',
                    color: 'white',
                    cursor: 'pointer',
                    width: '24px',
                    height: '24px',
                    borderRadius: '3px',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontSize: '18px'
                  }}
                >
                  −
                </button>
              )}
              {closeButton && (
                <button
                  onClick={handleClose}
                  style={{
                    background: 'transparent',
                    border: '1px solid rgba(255,255,255,0.3)',
                    color: 'white',
                    cursor: 'pointer',
                    width: '24px',
                    height: '24px',
                    borderRadius: '3px',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontSize: '18px'
                  }}
                >
                  ×
                </button>
              )}
            </div>
          </div>
        )}

        {/* Child buttons row */}
        <div
          className="child-buttons-container"
          style={{
            display: 'flex',
            justifyContent: 'center',
            marginBottom: '10px',
            width: '100%',
            flexWrap: 'wrap',
            gap: '2px',
            minHeight: '50px'
          }}
        >
          {Array.from({ length: 8 }).map((_, i) => {
            const char = currentChildren[i];
            const isActive = char && activeFamily;

            return (
              <button
                key={i}
                className="keyboard-child-button"
                style={{
                  margin: '2px',
                  padding: '10px',
                  minWidth: '40px',
                  minHeight: '40px',
                  fontSize: '18px',
                  cursor: 'pointer',
                  background: isActive ? '#d3d3d3' : '#e0e0e0',
                  border: '1px solid #ccc',
                  borderRadius: '3px',
                  opacity: char ? 1 : 0.5,
                  transition: 'all 0.2s',
                  boxShadow: char ? '0 2px 4px rgba(0,0,0,0.1)' : 'none'
                }}
                onMouseEnter={(e) => {
                  if (char) e.currentTarget.style.background = '#339af0';
                }}
                onMouseLeave={(e) => {
                  if (char) e.currentTarget.style.background = '#d3d3d3';
                }}
                onClick={() => char && handleChildButtonClick(char, i)}
              >
                {char || ''}
              </button>
            );
          })}
        </div>

        {/* Main keyboard rows */}
        {layout.map((row, rowIndex) => (
          <div
            key={rowIndex}
            className="keyboard-row"
            style={{
              display: 'flex',
              justifyContent: 'center',
              marginBottom: '5px',
              width: '100%',
              flexWrap: 'nowrap',
              flexShrink: 0
            }}
          >
            {row.map((key, keyIndex) => (
              <button
                key={keyIndex}
                className="keyboard-key"
                style={{
                  margin: '2px',
                  padding: '8px',
                  minWidth: '35px',
                  minHeight: '40px',
                  fontSize: 'clamp(14px, 1.5vw, 18px)',
                  cursor: 'pointer',
                  border: '1px solid #ccc',
                  borderRadius: '3px',
                  background: 'white',
                  transition: 'all 0.2s',
                  flex: 1,
                  maxWidth: key.type === 'space' ? '150px' : '70px',
                  boxSizing: 'border-box'
                }}
                onMouseEnter={(e) => {
                  if (key.type === 'char') {
                    e.currentTarget.style.background = '#339af0';
                    e.currentTarget.style.color = 'white';
                  }
                }}
                onMouseLeave={(e) => {
                  if (key.type === 'char') {
                    e.currentTarget.style.background = 'white';
                    e.currentTarget.style.color = 'black';
                  }
                }}
                onClick={() => handleKeyPress(key)}
              >
                {key.label}
              </button>
            ))}
          </div>
        ))}

        {/* Children slot */}
        {children}

        {/* Resize handle */}
        <div
          ref={resizeHandleRef}
          className="resize-handle"
          style={{
            position: 'absolute',
            bottom: 0,
            right: 0,
            width: '20px',
            height: '20px',
            cursor: 'se-resize',
            background: 'linear-gradient(135deg, transparent 50%, #888 50%)',
            borderRadius: '0 0 5px 0',
            zIndex: 10001,
            opacity: 0.7,
            transition: 'opacity 0.2s'
          }}
          onMouseEnter={() => {
            if (resizeHandleRef.current) {
              resizeHandleRef.current.style.opacity = '1';
            }
          }}
          onMouseLeave={() => {
            if (resizeHandleRef.current && !isResizing) {
              resizeHandleRef.current.style.opacity = '0.7';
            }
          }}
          onMouseDown={handleResizeStart}
        />
      </div>
    );
  }
);

AmharicKeyboard.displayName = 'AmharicKeyboard';
